### ISSUE TITLE
Impliment mailgun 

### ISSUE THREAD

**Issue by AlecTroemel** [whmountains/mailgun-rs#1]
why is this published to crate.io if there isn't anything? If you don't plan on working on this, I'd like to take it over.

**Comment by whmountains** [comment]
This crate was going to be a component of a project I was developing for a client.  The project was put on hold and I got busy with other stuff.

I've added a note in the Readme so people don't get confused.

I'll happily give you ownership of the package if you have a working mailgun client to put in it's place.
